let classmates = ["철수", "영희", "훈이"];
["철수", "영희", "훈이"];
classmates[0];
("철수");
classmates[1];
("영희");
classmates[2];
("훈이");
classmates.includes("훈이");
true;
classmates.includes("맹구");
false;
classmates.length;
3;
classmates.push("맹구");
4;
classmates.includes("맹구");
true;
classmates(4)[("철수", "영희", "훈이", "맹구")];
classmates.pop();
("맹구");
classmates(3)[("철수", "영희", "훈이")];

const email = "codecamp@gmail.com";
undefined;
email.includes("@");
true;
email.split("@");
(2)[("codecamp", "gmail.com")];
let splite = email.split("@");
undefined;
splite(2)[("codecamp", "gmail.com")];
let splite = email.split("@")[0];
undefined;
splite;
("codecamp");
let company = email.split("@")[1];
undefined;
let maskingmail = [];
undefined;
maskingmail.push(splite[0]);
1;
maskingmail.push(splite[1]);
2;
maskingmail.push(splite[2]);
3;
maskingmail.push(splite[3]);
4;
maskingmail(4)[("c", "o", "d", "e")];
maskingmail.push("*");
5;
maskingmail.push("*");
6;
maskingmail.push("*");
7;
maskingmail.push("*");
8;
maskingmail.join("");
("code****");
maskingmail.join("") + "@" + company;
("code****@gmail.com");
let result = maskingmail.join("") + "@" + company;
undefined;
result;
("code****@gmail.com");
